#!/bin/bash

#docker versions
VERSIONS=( 1.0.0 1.0.1 1.1.0 1.1.1 1.1.2 1.2.0 1.3.0 1.3.1 1.3.2 1.3.3 1.4.0 1.4.1 1.5.0 1.6.0 1.6.1 1.6.2 1.7.0 1.7.1 )
BINNAME=docker

RUNNER=`basename $0`

if [ "$RUNNER" = "dockercomposeswitch" ]; then
    BINNAME="docker-compose"
    VERSIONS=( 1.4.0 1.3.3 1.3.2 1.3.1 1.3.0 1.2.0 )
fi

DSDIR=/opt/dockerswitch

EXECUTABLE=/usr/bin/${BINNAME}
[ "$(uname -s)" = "Darwin" ] && EXECUTABLE=/usr/local/bin/${BINNAME}

usage () {
    echo use as: $0 "<VERSION>"
    echo VERSION can be one of: "${VERSIONS[@]}"
    exit 1
}

getversion () {
    mkdir -p $DSDIR
    V=$1
    F=${DSDIR}/${BINNAME}-${V}

    URL="https://get.docker.com/builds/`uname -s`/`uname -m`/${BINNAME}-${V}"
    if [ "$RUNNER" = "dockercomposeswitch" ]; then
        URL="https://github.com/docker/compose/releases/download/${V}/docker-compose-`uname -s`-`uname -m`"
    fi
    curl -f -L ${URL} -o "$F"
    if [ $? -ne 0 ]; then
        echo "problem downloading from $URL"
        exit 1
    fi
    chmod +x "$F"
}

contains () {
    local e
    for e in "${@:2}"; do
        [[ "$e" == "$1" ]] && return 0
    done
    return 1
}

if [ $# -eq 0 ]; then
    if [ ! -L "$EXECUTABLE" ]; then
        echo $EXECUTABLE is not symlink, you did not use dockerswitch yet
    else
        echo "Currrently linked to $EXECUTABLE is:"
        readlink $EXECUTABLE
    fi
    exit 0 
fi

if [ $# -ne 1 ]; then
    usage
fi

if ! contains "$1" "${VERSIONS[@]}"; then
    echo "Wrong version: $1"
    usage
fi

if [ ! "`id -u`" = "0" ]; then
    echo "you must run version switch with sudo, or as root"
    usage
fi

F="$DSDIR/${BINNAME}-${1}"

[ -f "$F" ] || getversion $1
if [ ! -L "$EXECUTABLE" ]; then
    echo moving $EXECUTABLE to ${EXECUTABLE}.old
    mv $EXECUTABLE ${EXECUTABLE}.old
fi
rm -f $EXECUTABLE
echo linking $F to $EXECUTABLE
ln -s $F $EXECUTABLE
