#!/bin/bash

DOCKER_VERSIONS=( 1.0.0 1.0.1 1.1.0 1.1.1 1.1.2 1.2.0 1.3.0 1.3.1 1.3.2 1.3.3 1.4.0 1.4.1 1.5.0 1.6.0 1.6.1 1.6.2 1.7.0 1.7.1 )

DSDIR=/opt/dockerswitch

EXECUTABLE=/usr/bin/docker

usage () {
    echo use as: $0 "<VERSION>"
    echo VERSION can be one of: "${DOCKER_VERSIONS[@]}"
    exit 1
}

getversion () {
    mkdir -p $DSDIR
    V=$1
    F=${DSDIR}/docker-${V}
    BLDS="https://get.docker.com/builds"
    curl -L ${BLDS}/`uname -s`/`uname -m`/docker-${V} -o "$F"
    chmod +x "$F"
}

contains () {
    local e
    for e in "${@:2}"; do
        [[ "$e" == "$1" ]] && return 0
    done
    return 1
}

if [ $# -eq 0 ]; then
    if [ ! -L "$EXECUTABLE" ]; then
        echo $EXECUTABLE is not symlink, you did not use dockerswitch yet
    else
        echo basename `readlink $EXECUTABLE` | cut -f 2 -d'-'
    fi
    exit 0 
fi

if [ $# -ne 1 ]; then
    usage
fi

if ! contains "$1" "${DOCKER_VERSIONS[@]}"; then
    echo "Wrong version: $1"
    usage
fi

if [ ! "`id -u`" = "0" ]; then
    echo "you must run version switch with sudo, or as root"
    usage
fi

F="$DSDIR/docker-${1}"

[ -f "$F" ] || getversion $1
if [ ! -L "$EXECUTABLE" ]; then
    echo moving /usr/bin/docker to /usr/bin/docker.old
    mv $EXECUTABLE /usr/bin/docker.old
fi
rm -f $EXECUTABLE
echo linking $F to $EXECUTABLE
ln -s $F $EXECUTABLE
